//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class pml {
    
    private head headField;
    
    private body[] bodyField;
    
    /// <remarks/>
    public head head {
        get {
            return this.headField;
        }
        set {
            this.headField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("body")]
    public body[] body {
        get {
            return this.bodyField;
        }
        set {
            this.bodyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class head {
    
    private timeStamp timeStampField;
    
    private source sourceField;
    
    /// <remarks/>
    public timeStamp timeStamp {
        get {
            return this.timeStampField;
        }
        set {
            this.timeStampField = value;
        }
    }
    
    /// <remarks/>
    public source source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class timeStamp {
    
    private System.DateTime valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class source {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class body {
    
    private layer1 layer1Field;
    
    private layer2 layer2Field;
    
    private string idField;
    
    private double genderField;
    
    private double ageField;
    
    /// <remarks/>
    public layer1 layer1 {
        get {
            return this.layer1Field;
        }
        set {
            this.layer1Field = value;
        }
    }
    
    /// <remarks/>
    public layer2 layer2 {
        get {
            return this.layer2Field;
        }
        set {
            this.layer2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double gender {
        get {
            return this.genderField;
        }
        set {
            this.genderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double age {
        get {
            return this.ageField;
        }
        set {
            this.ageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class layer1 {
    
    private presence presenceField;
    
    private smileFrequency smileFrequencyField;
    
    private activity activityField;
    
    private attention attentionField;
    
    private agreement agreementField;
    
    private engagement engagementField;
    
    private anxiety anxietyField;
    
    /// <remarks/>
    public presence presence {
        get {
            return this.presenceField;
        }
        set {
            this.presenceField = value;
        }
    }
    
    /// <remarks/>
    public smileFrequency smileFrequency {
        get {
            return this.smileFrequencyField;
        }
        set {
            this.smileFrequencyField = value;
        }
    }
    
    /// <remarks/>
    public activity activity {
        get {
            return this.activityField;
        }
        set {
            this.activityField = value;
        }
    }
    
    /// <remarks/>
    public attention attention {
        get {
            return this.attentionField;
        }
        set {
            this.attentionField = value;
        }
    }
    
    /// <remarks/>
    public agreement agreement {
        get {
            return this.agreementField;
        }
        set {
            this.agreementField = value;
        }
    }
    
    /// <remarks/>
    public engagement engagement {
        get {
            return this.engagementField;
        }
        set {
            this.engagementField = value;
        }
    }
    
    /// <remarks/>
    public anxiety anxiety {
        get {
            return this.anxietyField;
        }
        set {
            this.anxietyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class presence {
    
    private presenceType presenceTypeField;
    
    private double confidenceField;
    
    private bool confidenceFieldSpecified;
    
    private conf_str conf_strField;
    
    private bool conf_strFieldSpecified;
    
    /// <remarks/>
    public presenceType presenceType {
        get {
            return this.presenceTypeField;
        }
        set {
            this.presenceTypeField = value;
        }
    }
    
    /// <remarks/>
    public double confidence {
        get {
            return this.confidenceField;
        }
        set {
            this.confidenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool confidenceSpecified {
        get {
            return this.confidenceFieldSpecified;
        }
        set {
            this.confidenceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public conf_str conf_str {
        get {
            return this.conf_strField;
        }
        set {
            this.conf_strField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool conf_strSpecified {
        get {
            return this.conf_strFieldSpecified;
        }
        set {
            this.conf_strFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public enum presenceType {
    
    /// <remarks/>
    present,
    
    /// <remarks/>
    not_present,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public enum conf_str {
    
    /// <remarks/>
    confident,
    
    /// <remarks/>
    not_confident,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class smileFrequency {
    
    private behaviorType behaviorTypeField;
    
    private double smilesField;
    
    private bool smilesFieldSpecified;
    
    private double confidenceField;
    
    private bool confidenceFieldSpecified;
    
    private conf_str conf_strField;
    
    private bool conf_strFieldSpecified;
    
    /// <remarks/>
    public behaviorType behaviorType {
        get {
            return this.behaviorTypeField;
        }
        set {
            this.behaviorTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public double smiles {
        get {
            return this.smilesField;
        }
        set {
            this.smilesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool smilesSpecified {
        get {
            return this.smilesFieldSpecified;
        }
        set {
            this.smilesFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public double confidence {
        get {
            return this.confidenceField;
        }
        set {
            this.confidenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool confidenceSpecified {
        get {
            return this.confidenceFieldSpecified;
        }
        set {
            this.confidenceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public conf_str conf_str {
        get {
            return this.conf_strField;
        }
        set {
            this.conf_strField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool conf_strSpecified {
        get {
            return this.conf_strFieldSpecified;
        }
        set {
            this.conf_strFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public enum behaviorType {
    
    /// <remarks/>
    high,
    
    /// <remarks/>
    mid,
    
    /// <remarks/>
    low,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class activity {
    
    private behaviorType behaviorTypeField;
    
    private double confidenceField;
    
    private bool confidenceFieldSpecified;
    
    private conf_str conf_strField;
    
    private bool conf_strFieldSpecified;
    
    /// <remarks/>
    public behaviorType behaviorType {
        get {
            return this.behaviorTypeField;
        }
        set {
            this.behaviorTypeField = value;
        }
    }
    
    /// <remarks/>
    public double confidence {
        get {
            return this.confidenceField;
        }
        set {
            this.confidenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool confidenceSpecified {
        get {
            return this.confidenceFieldSpecified;
        }
        set {
            this.confidenceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public conf_str conf_str {
        get {
            return this.conf_strField;
        }
        set {
            this.conf_strField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool conf_strSpecified {
        get {
            return this.conf_strFieldSpecified;
        }
        set {
            this.conf_strFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class attention {
    
    private behaviorType behaviorTypeField;
    
    private double behaviorValueField;
    
    private bool behaviorValueFieldSpecified;
    
    private double confidenceField;
    
    private bool confidenceFieldSpecified;
    
    private conf_str conf_strField;
    
    private bool conf_strFieldSpecified;
    
    /// <remarks/>
    public behaviorType behaviorType {
        get {
            return this.behaviorTypeField;
        }
        set {
            this.behaviorTypeField = value;
        }
    }
    
    /// <remarks/>
    public double behaviorValue {
        get {
            return this.behaviorValueField;
        }
        set {
            this.behaviorValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool behaviorValueSpecified {
        get {
            return this.behaviorValueFieldSpecified;
        }
        set {
            this.behaviorValueFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public double confidence {
        get {
            return this.confidenceField;
        }
        set {
            this.confidenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool confidenceSpecified {
        get {
            return this.confidenceFieldSpecified;
        }
        set {
            this.confidenceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public conf_str conf_str {
        get {
            return this.conf_strField;
        }
        set {
            this.conf_strField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool conf_strSpecified {
        get {
            return this.conf_strFieldSpecified;
        }
        set {
            this.conf_strFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class agreement {
    
    private behaviorType behaviorTypeField;
    
    private double behaviorValueField;
    
    private bool behaviorValueFieldSpecified;
    
    private double confidenceField;
    
    private bool confidenceFieldSpecified;
    
    private conf_str conf_strField;
    
    private bool conf_strFieldSpecified;
    
    /// <remarks/>
    public behaviorType behaviorType {
        get {
            return this.behaviorTypeField;
        }
        set {
            this.behaviorTypeField = value;
        }
    }
    
    /// <remarks/>
    public double behaviorValue {
        get {
            return this.behaviorValueField;
        }
        set {
            this.behaviorValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool behaviorValueSpecified {
        get {
            return this.behaviorValueFieldSpecified;
        }
        set {
            this.behaviorValueFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public double confidence {
        get {
            return this.confidenceField;
        }
        set {
            this.confidenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool confidenceSpecified {
        get {
            return this.confidenceFieldSpecified;
        }
        set {
            this.confidenceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public conf_str conf_str {
        get {
            return this.conf_strField;
        }
        set {
            this.conf_strField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool conf_strSpecified {
        get {
            return this.conf_strFieldSpecified;
        }
        set {
            this.conf_strFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class engagement {
    
    private behaviorType behaviorTypeField;
    
    private double behaviorValueField;
    
    private bool behaviorValueFieldSpecified;
    
    private double confidenceField;
    
    private bool confidenceFieldSpecified;
    
    private conf_str conf_strField;
    
    private bool conf_strFieldSpecified;
    
    /// <remarks/>
    public behaviorType behaviorType {
        get {
            return this.behaviorTypeField;
        }
        set {
            this.behaviorTypeField = value;
        }
    }
    
    /// <remarks/>
    public double behaviorValue {
        get {
            return this.behaviorValueField;
        }
        set {
            this.behaviorValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool behaviorValueSpecified {
        get {
            return this.behaviorValueFieldSpecified;
        }
        set {
            this.behaviorValueFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public double confidence {
        get {
            return this.confidenceField;
        }
        set {
            this.confidenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool confidenceSpecified {
        get {
            return this.confidenceFieldSpecified;
        }
        set {
            this.confidenceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public conf_str conf_str {
        get {
            return this.conf_strField;
        }
        set {
            this.conf_strField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool conf_strSpecified {
        get {
            return this.conf_strFieldSpecified;
        }
        set {
            this.conf_strFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class anxiety {
    
    private behaviorType behaviorTypeField;
    
    private double behaviorValueField;
    
    private bool behaviorValueFieldSpecified;
    
    private double confidenceField;
    
    private bool confidenceFieldSpecified;
    
    private conf_str conf_strField;
    
    private bool conf_strFieldSpecified;
    
    /// <remarks/>
    public behaviorType behaviorType {
        get {
            return this.behaviorTypeField;
        }
        set {
            this.behaviorTypeField = value;
        }
    }
    
    /// <remarks/>
    public double behaviorValue {
        get {
            return this.behaviorValueField;
        }
        set {
            this.behaviorValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool behaviorValueSpecified {
        get {
            return this.behaviorValueFieldSpecified;
        }
        set {
            this.behaviorValueFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public double confidence {
        get {
            return this.confidenceField;
        }
        set {
            this.confidenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool confidenceSpecified {
        get {
            return this.confidenceFieldSpecified;
        }
        set {
            this.confidenceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public conf_str conf_str {
        get {
            return this.conf_strField;
        }
        set {
            this.conf_strField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool conf_strSpecified {
        get {
            return this.conf_strFieldSpecified;
        }
        set {
            this.conf_strFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class layer2 {
    
    private posture[] postureField;
    
    private faceGesture[] faceGestureField;
    
    private headPose headPoseField;
    
    private handPoseLeft handPoseLeftField;
    
    private handPoseRight handPoseRightField;
    
    private faceGaze faceGazeField;
    
    private eyeGaze eyeGazeField;
    
    private headGesture[] headGestureField;
    
    private handGesture[] handGestureField;
    
    private armLeft[] armLeftField;
    
    private armRight[] armRightField;
    
    private speechFraction[] speechFractionField;
    
    private speechVariation[] speechVariationField;
    
    private speechRate[] speechRateField;

    // add skeleton by JUN
    private skeleton skeletonField;
    
    /// <remarks/>
    public skeleton skeleton {
        get {
            return this.skeletonField;
        }
        set {
            this.skeletonField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("posture")]
    public posture[] posture {
        get {
            return this.postureField;
        }
        set {
            this.postureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("faceGesture")]
    public faceGesture[] faceGesture {
        get {
            return this.faceGestureField;
        }
        set {
            this.faceGestureField = value;
        }
    }
    
    /// <remarks/>
    public headPose headPose {
        get {
            return this.headPoseField;
        }
        set {
            this.headPoseField = value;
        }
    }
    
    /// <remarks/>
    public handPoseLeft handPoseLeft {
        get {
            return this.handPoseLeftField;
        }
        set {
            this.handPoseLeftField = value;
        }
    }
    
    /// <remarks/>
    public handPoseRight handPoseRight {
        get {
            return this.handPoseRightField;
        }
        set {
            this.handPoseRightField = value;
        }
    }
    
    /// <remarks/>
    public faceGaze faceGaze {
        get {
            return this.faceGazeField;
        }
        set {
            this.faceGazeField = value;
        }
    }
    
    /// <remarks/>
    public eyeGaze eyeGaze {
        get {
            return this.eyeGazeField;
        }
        set {
            this.eyeGazeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("headGesture")]
    public headGesture[] headGesture {
        get {
            return this.headGestureField;
        }
        set {
            this.headGestureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("handGesture")]
    public handGesture[] handGesture {
        get {
            return this.handGestureField;
        }
        set {
            this.handGestureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("armLeft")]
    public armLeft[] armLeft {
        get {
            return this.armLeftField;
        }
        set {
            this.armLeftField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("armRight")]
    public armRight[] armRight {
        get {
            return this.armRightField;
        }
        set {
            this.armRightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("speechFraction")]
    public speechFraction[] speechFraction {
        get {
            return this.speechFractionField;
        }
        set {
            this.speechFractionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("speechVariation")]
    public speechVariation[] speechVariation {
        get {
            return this.speechVariationField;
        }
        set {
            this.speechVariationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("speechRate")]
    public speechRate[] speechRate {
        get {
            return this.speechRateField;
        }
        set {
            this.speechRateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class posture {
    
    private postureType postureTypeField;
    
    private postureStatus postureStatusField;
    
    private bool postureStatusFieldSpecified;
    
    private double postureDegreeField;
    
    private bool postureDegreeFieldSpecified;
    
    private double confidenceField;
    
    private bool confidenceFieldSpecified;
    
    private conf_str conf_strField;
    
    private bool conf_strFieldSpecified;
    
    /// <remarks/>
    public postureType postureType {
        get {
            return this.postureTypeField;
        }
        set {
            this.postureTypeField = value;
        }
    }
    
    /// <remarks/>
    public postureStatus postureStatus {
        get {
            return this.postureStatusField;
        }
        set {
            this.postureStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool postureStatusSpecified {
        get {
            return this.postureStatusFieldSpecified;
        }
        set {
            this.postureStatusFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public double postureDegree {
        get {
            return this.postureDegreeField;
        }
        set {
            this.postureDegreeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool postureDegreeSpecified {
        get {
            return this.postureDegreeFieldSpecified;
        }
        set {
            this.postureDegreeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public double confidence {
        get {
            return this.confidenceField;
        }
        set {
            this.confidenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool confidenceSpecified {
        get {
            return this.confidenceFieldSpecified;
        }
        set {
            this.confidenceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public conf_str conf_str {
        get {
            return this.conf_strField;
        }
        set {
            this.conf_strField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool conf_strSpecified {
        get {
            return this.conf_strFieldSpecified;
        }
        set {
            this.conf_strFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public enum postureType {
    
    /// <remarks/>
    leaning_forward,
    
    /// <remarks/>
    leaning_backward,
    
    /// <remarks/>
    upright,
    
    /// <remarks/>
    tilted,
    
    /// <remarks/>
    rocking,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public enum postureStatus {
    
    /// <remarks/>
    sitting,
    
    /// <remarks/>
    standing,
    
    /// <remarks/>
    walking,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class faceGesture {
    
    private faceGestureType faceGestureTypeField;
    
    private bool gestureBoolField;
    
    private bool gestureBoolFieldSpecified;
    
    private double gestureValueField;
    
    private bool gestureValueFieldSpecified;
    
    private double confidenceField;
    
    private bool confidenceFieldSpecified;
    
    private conf_str conf_strField;
    
    private bool conf_strFieldSpecified;
    
    /// <remarks/>
    public faceGestureType faceGestureType {
        get {
            return this.faceGestureTypeField;
        }
        set {
            this.faceGestureTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool gestureBool {
        get {
            return this.gestureBoolField;
        }
        set {
            this.gestureBoolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool gestureBoolSpecified {
        get {
            return this.gestureBoolFieldSpecified;
        }
        set {
            this.gestureBoolFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public double gestureValue {
        get {
            return this.gestureValueField;
        }
        set {
            this.gestureValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool gestureValueSpecified {
        get {
            return this.gestureValueFieldSpecified;
        }
        set {
            this.gestureValueFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public double confidence {
        get {
            return this.confidenceField;
        }
        set {
            this.confidenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool confidenceSpecified {
        get {
            return this.confidenceFieldSpecified;
        }
        set {
            this.confidenceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public conf_str conf_str {
        get {
            return this.conf_strField;
        }
        set {
            this.conf_strField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool conf_strSpecified {
        get {
            return this.conf_strFieldSpecified;
        }
        set {
            this.conf_strFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public enum faceGestureType {
    
    /// <remarks/>
    smile,
    
    /// <remarks/>
    leftEyeClosed,
    
    /// <remarks/>
    rightEyeClosed,
    
    /// <remarks/>
    mouthOpen,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class headPose {
    
    private position positionField;
    
    private poseType poseTypeField;
    
    private bool poseTypeFieldSpecified;
    
    private rotation rotationField;
    
    private double confidenceField;
    
    private bool confidenceFieldSpecified;
    
    private conf_str conf_strField;
    
    private bool conf_strFieldSpecified;
    
    /// <remarks/>
    public position position {
        get {
            return this.positionField;
        }
        set {
            this.positionField = value;
        }
    }
    
    /// <remarks/>
    public poseType poseType {
        get {
            return this.poseTypeField;
        }
        set {
            this.poseTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool poseTypeSpecified {
        get {
            return this.poseTypeFieldSpecified;
        }
        set {
            this.poseTypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public rotation rotation {
        get {
            return this.rotationField;
        }
        set {
            this.rotationField = value;
        }
    }
    
    /// <remarks/>
    public double confidence {
        get {
            return this.confidenceField;
        }
        set {
            this.confidenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool confidenceSpecified {
        get {
            return this.confidenceFieldSpecified;
        }
        set {
            this.confidenceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public conf_str conf_str {
        get {
            return this.conf_strField;
        }
        set {
            this.conf_strField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool conf_strSpecified {
        get {
            return this.conf_strFieldSpecified;
        }
        set {
            this.conf_strFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class position {
    
    private double xField;
    
    private double yField;
    
    private double zField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double x {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double z {
        get {
            return this.zField;
        }
        set {
            this.zField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public enum poseType {
    
    /// <remarks/>
    moving,
    
    /// <remarks/>
    not_moving,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class rotation {
    
    private double rotXField;
    
    private double rotYField;
    
    private double rotZField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double rotX {
        get {
            return this.rotXField;
        }
        set {
            this.rotXField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double rotY {
        get {
            return this.rotYField;
        }
        set {
            this.rotYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double rotZ {
        get {
            return this.rotZField;
        }
        set {
            this.rotZField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class handPoseLeft {
    
    private position positionField;
    
    private poseType poseTypeField;
    
    private bool poseTypeFieldSpecified;
    
    private rotation rotationField;
    
    private double confidenceField;
    
    private bool confidenceFieldSpecified;
    
    private conf_str conf_strField;
    
    private bool conf_strFieldSpecified;
    
    /// <remarks/>
    public position position {
        get {
            return this.positionField;
        }
        set {
            this.positionField = value;
        }
    }
    
    /// <remarks/>
    public poseType poseType {
        get {
            return this.poseTypeField;
        }
        set {
            this.poseTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool poseTypeSpecified {
        get {
            return this.poseTypeFieldSpecified;
        }
        set {
            this.poseTypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public rotation rotation {
        get {
            return this.rotationField;
        }
        set {
            this.rotationField = value;
        }
    }
    
    /// <remarks/>
    public double confidence {
        get {
            return this.confidenceField;
        }
        set {
            this.confidenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool confidenceSpecified {
        get {
            return this.confidenceFieldSpecified;
        }
        set {
            this.confidenceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public conf_str conf_str {
        get {
            return this.conf_strField;
        }
        set {
            this.conf_strField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool conf_strSpecified {
        get {
            return this.conf_strFieldSpecified;
        }
        set {
            this.conf_strFieldSpecified = value;
        }
    }
}

/// <remarks/>
/// Added by Jun
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class skeleton
{
    private joint[] jointField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("joint")]
    public joint[] joint
    {
        get
        {
            return this.jointField;
        }
        set
        {
            this.jointField = value;
        }
    }
}

/// <remarks/>
/// Added by Jun
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class joint
{
    private position positionField;

    private rotation rotationField;

    private double jointConfidenceField;

    private string jointNameField;

    /// <remarks/>
    public position position {
        get
        {
            return this.positionField;
        }
        set
        {
            this.positionField = value;
        }
    }

    public rotation rotation
    {
        get
        {
            return this.rotationField;
        }
        set
        {
            this.rotationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double jointConfidence
    {
        get
        {
            return this.jointConfidenceField;
        }
        set
        {
            this.jointConfidenceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string jointName
    {
        get
        {
            return this.jointNameField;
        }
        set
        {
            this.jointNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class handPoseRight {
    
    private position positionField;
    
    private poseType poseTypeField;
    
    private bool poseTypeFieldSpecified;
    
    private rotation rotationField;
    
    private double confidenceField;
    
    private bool confidenceFieldSpecified;
    
    private conf_str conf_strField;
    
    private bool conf_strFieldSpecified;
    
    /// <remarks/>
    public position position {
        get {
            return this.positionField;
        }
        set {
            this.positionField = value;
        }
    }
    
    /// <remarks/>
    public poseType poseType {
        get {
            return this.poseTypeField;
        }
        set {
            this.poseTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool poseTypeSpecified {
        get {
            return this.poseTypeFieldSpecified;
        }
        set {
            this.poseTypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public rotation rotation {
        get {
            return this.rotationField;
        }
        set {
            this.rotationField = value;
        }
    }
    
    /// <remarks/>
    public double confidence {
        get {
            return this.confidenceField;
        }
        set {
            this.confidenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool confidenceSpecified {
        get {
            return this.confidenceFieldSpecified;
        }
        set {
            this.confidenceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public conf_str conf_str {
        get {
            return this.conf_strField;
        }
        set {
            this.conf_strField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool conf_strSpecified {
        get {
            return this.conf_strFieldSpecified;
        }
        set {
            this.conf_strFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class faceGaze {
    
    private gazeCategoryHorizontal gazeCategoryHorizontalField;
    
    private gazeCategoryVertical gazeCategoryVerticalField;
    
    private gazeCategoryDirection gazeCategoryDirectionField;
    
    private double confidenceField;
    
    private bool confidenceFieldSpecified;
    
    private conf_str conf_strField;
    
    private bool conf_strFieldSpecified;
    
    /// <remarks/>
    public gazeCategoryHorizontal gazeCategoryHorizontal {
        get {
            return this.gazeCategoryHorizontalField;
        }
        set {
            this.gazeCategoryHorizontalField = value;
        }
    }
    
    /// <remarks/>
    public gazeCategoryVertical gazeCategoryVertical {
        get {
            return this.gazeCategoryVerticalField;
        }
        set {
            this.gazeCategoryVerticalField = value;
        }
    }
    
    /// <remarks/>
    public gazeCategoryDirection gazeCategoryDirection {
        get {
            return this.gazeCategoryDirectionField;
        }
        set {
            this.gazeCategoryDirectionField = value;
        }
    }
    
    /// <remarks/>
    public double confidence {
        get {
            return this.confidenceField;
        }
        set {
            this.confidenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool confidenceSpecified {
        get {
            return this.confidenceFieldSpecified;
        }
        set {
            this.confidenceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public conf_str conf_str {
        get {
            return this.conf_strField;
        }
        set {
            this.conf_strField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool conf_strSpecified {
        get {
            return this.conf_strFieldSpecified;
        }
        set {
            this.conf_strFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public enum gazeCategoryHorizontal {
    
    /// <remarks/>
    left,
    
    /// <remarks/>
    right,
    
    /// <remarks/>
    central,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public enum gazeCategoryVertical {
    
    /// <remarks/>
    up,
    
    /// <remarks/>
    down,
    
    /// <remarks/>
    central,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public enum gazeCategoryDirection {
    
    /// <remarks/>
    towards,
    
    /// <remarks/>
    away,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class eyeGaze {
    
    private gazeCategoryHorizontal gazeCategoryHorizontalField;
    
    private gazeCategoryVertical gazeCategoryVerticalField;
    
    private gazeCategoryDirection gazeCategoryDirectionField;
    
    private double confidenceField;
    
    private bool confidenceFieldSpecified;
    
    private conf_str conf_strField;
    
    private bool conf_strFieldSpecified;
    
    /// <remarks/>
    public gazeCategoryHorizontal gazeCategoryHorizontal {
        get {
            return this.gazeCategoryHorizontalField;
        }
        set {
            this.gazeCategoryHorizontalField = value;
        }
    }
    
    /// <remarks/>
    public gazeCategoryVertical gazeCategoryVertical {
        get {
            return this.gazeCategoryVerticalField;
        }
        set {
            this.gazeCategoryVerticalField = value;
        }
    }
    
    /// <remarks/>
    public gazeCategoryDirection gazeCategoryDirection {
        get {
            return this.gazeCategoryDirectionField;
        }
        set {
            this.gazeCategoryDirectionField = value;
        }
    }
    
    /// <remarks/>
    public double confidence {
        get {
            return this.confidenceField;
        }
        set {
            this.confidenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool confidenceSpecified {
        get {
            return this.confidenceFieldSpecified;
        }
        set {
            this.confidenceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public conf_str conf_str {
        get {
            return this.conf_strField;
        }
        set {
            this.conf_strField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool conf_strSpecified {
        get {
            return this.conf_strFieldSpecified;
        }
        set {
            this.conf_strFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class headGesture {
    
    private headGestureType headGestureTypeField;
    
    private double confidenceField;
    
    private bool confidenceFieldSpecified;
    
    private conf_str conf_strField;
    
    private bool conf_strFieldSpecified;
    
    /// <remarks/>
    public headGestureType headGestureType {
        get {
            return this.headGestureTypeField;
        }
        set {
            this.headGestureTypeField = value;
        }
    }
    
    /// <remarks/>
    public double confidence {
        get {
            return this.confidenceField;
        }
        set {
            this.confidenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool confidenceSpecified {
        get {
            return this.confidenceFieldSpecified;
        }
        set {
            this.confidenceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public conf_str conf_str {
        get {
            return this.conf_strField;
        }
        set {
            this.conf_strField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool conf_strSpecified {
        get {
            return this.conf_strFieldSpecified;
        }
        set {
            this.conf_strFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public enum headGestureType {
    
    /// <remarks/>
    nod,
    
    /// <remarks/>
    shake,
    
    /// <remarks/>
    glanceLeft,
    
    /// <remarks/>
    glanceRight,
    
    /// <remarks/>
    glanceUp,
    
    /// <remarks/>
    glanceDown,
    
    /// <remarks/>
    @static,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class handGesture {
    
    private handGestureType handGestureTypeField;
    
    private double confidenceField;
    
    private bool confidenceFieldSpecified;
    
    private conf_str conf_strField;
    
    private bool conf_strFieldSpecified;
    
    /// <remarks/>
    public handGestureType handGestureType {
        get {
            return this.handGestureTypeField;
        }
        set {
            this.handGestureTypeField = value;
        }
    }
    
    /// <remarks/>
    public double confidence {
        get {
            return this.confidenceField;
        }
        set {
            this.confidenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool confidenceSpecified {
        get {
            return this.confidenceFieldSpecified;
        }
        set {
            this.confidenceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public conf_str conf_str {
        get {
            return this.conf_strField;
        }
        set {
            this.conf_strField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool conf_strSpecified {
        get {
            return this.conf_strFieldSpecified;
        }
        set {
            this.conf_strFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public enum handGestureType {
    
    /// <remarks/>
    fidgeting,
    
    /// <remarks/>
    notFidgeting,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class armLeft {
    
    private armType armTypeField;
    
    private double confidenceField;
    
    private bool confidenceFieldSpecified;
    
    private conf_str conf_strField;
    
    private bool conf_strFieldSpecified;
    
    /// <remarks/>
    public armType armType {
        get {
            return this.armTypeField;
        }
        set {
            this.armTypeField = value;
        }
    }
    
    /// <remarks/>
    public double confidence {
        get {
            return this.confidenceField;
        }
        set {
            this.confidenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool confidenceSpecified {
        get {
            return this.confidenceFieldSpecified;
        }
        set {
            this.confidenceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public conf_str conf_str {
        get {
            return this.conf_strField;
        }
        set {
            this.conf_strField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool conf_strSpecified {
        get {
            return this.conf_strFieldSpecified;
        }
        set {
            this.conf_strFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public enum armType {
    
    /// <remarks/>
    hand_on_lap,
    
    /// <remarks/>
    hand_on_face,
    
    /// <remarks/>
    hand_on_side,
    
    /// <remarks/>
    closed_arms,
    
    /// <remarks/>
    moving,
    
    /// <remarks/>
    @static,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class armRight {
    
    private armType armTypeField;
    
    private double confidenceField;
    
    private bool confidenceFieldSpecified;
    
    private conf_str conf_strField;
    
    private bool conf_strFieldSpecified;
    
    /// <remarks/>
    public armType armType {
        get {
            return this.armTypeField;
        }
        set {
            this.armTypeField = value;
        }
    }
    
    /// <remarks/>
    public double confidence {
        get {
            return this.confidenceField;
        }
        set {
            this.confidenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool confidenceSpecified {
        get {
            return this.confidenceFieldSpecified;
        }
        set {
            this.confidenceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public conf_str conf_str {
        get {
            return this.conf_strField;
        }
        set {
            this.conf_strField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool conf_strSpecified {
        get {
            return this.conf_strFieldSpecified;
        }
        set {
            this.conf_strFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class speechFraction {
    
    private double speechFractionValueField;
    
    private double speechIntervalField;
    
    private double startTimeField;
    
    private double endTimeField;
    
    private double confidenceField;
    
    private bool confidenceFieldSpecified;
    
    private conf_str conf_strField;
    
    private bool conf_strFieldSpecified;
    
    /// <remarks/>
    public double speechFractionValue {
        get {
            return this.speechFractionValueField;
        }
        set {
            this.speechFractionValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public double speechInterval {
        get {
            return this.speechIntervalField;
        }
        set {
            this.speechIntervalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public double startTime {
        get {
            return this.startTimeField;
        }
        set {
            this.startTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public double endTime {
        get {
            return this.endTimeField;
        }
        set {
            this.endTimeField = value;
        }
    }
    
    /// <remarks/>
    public double confidence {
        get {
            return this.confidenceField;
        }
        set {
            this.confidenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool confidenceSpecified {
        get {
            return this.confidenceFieldSpecified;
        }
        set {
            this.confidenceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public conf_str conf_str {
        get {
            return this.conf_strField;
        }
        set {
            this.conf_strField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool conf_strSpecified {
        get {
            return this.conf_strFieldSpecified;
        }
        set {
            this.conf_strFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class speechVariation {
    
    private double speechVariationValueField;
    
    private double speechIntervalField;
    
    private double startTimeField;
    
    private double endTimeField;
    
    private double confidenceField;
    
    private bool confidenceFieldSpecified;
    
    private conf_str conf_strField;
    
    private bool conf_strFieldSpecified;
    
    /// <remarks/>
    public double speechVariationValue {
        get {
            return this.speechVariationValueField;
        }
        set {
            this.speechVariationValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public double speechInterval {
        get {
            return this.speechIntervalField;
        }
        set {
            this.speechIntervalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public double startTime {
        get {
            return this.startTimeField;
        }
        set {
            this.startTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public double endTime {
        get {
            return this.endTimeField;
        }
        set {
            this.endTimeField = value;
        }
    }
    
    /// <remarks/>
    public double confidence {
        get {
            return this.confidenceField;
        }
        set {
            this.confidenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool confidenceSpecified {
        get {
            return this.confidenceFieldSpecified;
        }
        set {
            this.confidenceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public conf_str conf_str {
        get {
            return this.conf_strField;
        }
        set {
            this.conf_strField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool conf_strSpecified {
        get {
            return this.conf_strFieldSpecified;
        }
        set {
            this.conf_strFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class speechRate {
    
    private double speechRateValueField;
    
    private double speechIntervalField;
    
    private double startTimeField;
    
    private double endTimeField;
    
    private double confidenceField;
    
    private bool confidenceFieldSpecified;
    
    private conf_str conf_strField;
    
    private bool conf_strFieldSpecified;
    
    /// <remarks/>
    public double speechRateValue {
        get {
            return this.speechRateValueField;
        }
        set {
            this.speechRateValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public double speechInterval {
        get {
            return this.speechIntervalField;
        }
        set {
            this.speechIntervalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public double startTime {
        get {
            return this.startTimeField;
        }
        set {
            this.startTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public double endTime {
        get {
            return this.endTimeField;
        }
        set {
            this.endTimeField = value;
        }
    }
    
    /// <remarks/>
    public double confidence {
        get {
            return this.confidenceField;
        }
        set {
            this.confidenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool confidenceSpecified {
        get {
            return this.confidenceFieldSpecified;
        }
        set {
            this.confidenceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public conf_str conf_str {
        get {
            return this.conf_strField;
        }
        set {
            this.conf_strField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool conf_strSpecified {
        get {
            return this.conf_strFieldSpecified;
        }
        set {
            this.conf_strFieldSpecified = value;
        }
    }
}
